### ISSUE TITLE
Support hashed email to prevent spam

### ISSUE THREAD

**Issue by kienpham2000** [formspree/formspree#110]
The email is in clear text, super easy for bot crawler to spam. I'm proposing to support like 

1) md5(email) of the email.

Currently support:
```
<form action="https://formspree.io/email@example.com" method="POST">
<input type="hidden" name="_cc" value="email2@example.com" />
```

And support this too?
```
<form action="https://formspree.io/23463b99b62a72f26ed677cc556c44e8" method="POST">
<input type="hidden" name="_cc" value="b75a7dd26f16ae13b440190aef177ac1" />
```

The system probably need to store this as part of the 1st email confirmation process

2) Or JWT where user send the key along for server to decode
```
<form action="https://formspree.io/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRoaXNpc2F0ZXN0QGdtYWlsLmNvbSJ9.VAvG3CwYzLZmM2EdGjvQ8YIAA0mIYCqcx5nPumTbI8A" method="POST">
<input type="hidden" name="_jwt_key" value="secret" />
```
This will prevent general crawler but not custom crawler

**Comment by colevscode** [comment]
I Ken. Great suggestion but I don't think we will implement it. We currently offer a honeypot to catch spammers, and provide a way to use random strings rather than email addresses for our gold users. I think an MD5 email adds complexity but doesn't provide sufficient additional security.
