### ISSUE TITLE
Duplicate form submissions

### ISSUE THREAD

**Issue by mikethehoffman** [formspree/formspree#111]
Starting last week I've been receiving duplicate form submissions from my website. Like today there are 6 identical forms from the same customer in India showing they were submitted on the same date and time. I have the form direct to a thankyou.html page on submission if that is relevant.

**Comment by rohitdatta** [comment]
We keep the Formspree repository for general feature requests and bugs that affect everyone. For your safety and security, please email [team@formspree.io](mailto:team@formspree.io) and include the details of your email address and site that is having the issue. We'll get back to you as soon as possible!
