### ISSUE TITLE
Name Attribute is Required?

### ISSUE THREAD

**Issue by krjordan** [formspree/formspree#64]
I am using a Bootstrap portfolio template that didn't include the name attributes in the form. When I added formspree, all I received was data from the `_replyto` field. After adding the `name` attribute to each of my `input` and `textarea` elements, it works as intended. So I am assuming the name attribute is required? If so, might be worth adding to the docs.

**Comment by rohitdatta** [comment]
Yes, that's correct, thanks for your suggestion. I'll add it to an FAQ section on the wiki, that will include this.
