### ISSUE TITLE
Modal window for form confirmation

### ISSUE THREAD

**Issue by akshaybharwani** [formspree/formspree#71]
Maybe an option that makes the confirmation window appear in a modal/pop-up window instead of a new tab?

**Comment by fiatjaf** [comment]
Which confirmation window? In the page that is implementing the form? We can't do it, it would require Javascript and we don't have access to that page. We only get the form submissions the page decides to send to us.

**Comment by rohitdatta** [comment]
While it would be possible, and we could write our own JavaScript file and have people import it, given that this is a one-time setup, I don't think it makes sense. In future, if people want to not be redirected to the Formspree page, you can just use an AJAX call.

**Comment by akshaybharwani** [comment]
This does makes sense. thanks!
