### ISSUE TITLE
Better Email Styling

### ISSUE THREAD

**Issue by rohitdatta** [formspree/formspree#74]
The current emails received are very basic. Should make them look much nicer

**Is this a bug or new feature?** New feature

**Reproduction Steps:**

None

**Expected behavior:**

Emails should be mobile responsive and also look better.

**Observed behavior:**

Emails are very simple

**Comment by lokenx** [comment]
Holy moly, nice job @rohitdatta ! Didn't realize until I got a new email just now! Now if only there was a silver plan that just hid the email address but none of the other features..lol
