### ISSUE TITLE
Use HTTPS everywhere

### ISSUE THREAD

**Issue by mcornella** [formspree/formspree#85]
The protocol-relative URL is an anti-pattern, as [Paul Irish put it](https://twitter.com/paul_irish/status/588502455530311680). All sample codes and documentation should switch to using `https://formspree.io`.

There are some other places of the documentation that use http as well, and the website works with http but a better behavior would be redirecting to the https website.

This is more of a feature request than a bug, but it's always nice seeing services adopt the HTTPS-only way ─or HTTPS by default, at least─. I'm assuming that a change of this magnitude needs to be tested extensively to ensure that the possibly higher CPU usage derived from HTTPS-only CPU usage doesn't make the service drive to a halt.

I've already started changing some things over at [mcornella/formspree@patch-1](https://github.com/mcornella/formspree/tree/patch-1), if you agree to this feature request I'll push the rest of the changes I've made and submit a PR.

Thanks!

**Comment by rohitdatta** [comment]
I'm 100% in favor of this. We should be doing our part to shift to a more secure web, and switching to HTTPS entirely would do so. I was working on this and was trying to think of all the possible bugs we may have, since we don't want to break the large number of people who are still using Formspree on HTTP. We need to make sure that anyone who submits to `http://formspree.io/email@email.com` will still be able to submit successfully, which I think we can do.

My thinking was that we would check the protocol for every request submitted and if it's HTTP, we change it to an HTTPS request. I'm not sure how this works however in returning a page.

I would like to change the documentation immediately where it doesn't at least use the protocol relative URL. Could you point out where you have found it directing users to use HTTP?

**Comment by rohitdatta** [comment]
@fiatjaf @colevscode What do you think about shifting to HTTPS everywhere?

**Comment by mcornella** [comment]
> I would like to change the documentation immediately where it doesn't at least use the protocol relative URL. Could you point out where you have found it directing users to use HTTP?

Not exactly instructing to use HTTP, but to use the protocol-relative URL (`//formspree.io`), which has the effect of using HTTP when the website that contains the form is delivered by HTTP. As I mention in the commit https://github.com/mcornella/formspree/commit/91bf9dfb19e6319a4466f7317bdfd3494dd2f903, the best-practice now is to use `https://` URLs. That involves changing:

* The README (https://github.com/mcornella/formspree/commit/91bf9dfb19e6319a4466f7317bdfd3494dd2f903)
* The sample forms of the website (https://github.com/mcornella/formspree/commit/c488dc0607d5e6b61288ef7f97fcbc8bebdc2e50).
  This last commit may have the side effect of breaking your website, since the `API_ROOT` env variable needs to be changed. Let me know if I should just fix this to not require the change of `API_ROOT`.

See the following screenshots of the [formspree.io](https://formspree.io) website as well:

![captura de pantalla de 2016-03-15 22-23-24](https://cloud.githubusercontent.com/assets/1441704/13794564/cfb72aac-eafc-11e5-948f-c511f96305a3.png)

![captura de pantalla de 2016-03-15 22-23-33](https://cloud.githubusercontent.com/assets/1441704/13794570/d629bada-eafc-11e5-98ad-010fbc7eca22.png)

![captura de pantalla de 2016-03-15 22-24-17](https://cloud.githubusercontent.com/assets/1441704/13794574/d9d44024-eafc-11e5-8225-b69534c14390.png)

Thanks for your swift response! :smile:

**Comment by rohitdatta** [comment]
Ahh I see what you're saying. Yeah even people who are writing sites that serve over HTTP can still submit to HTTPS endpoints, so if you can submit your documentation changes in a PR those could get merged in.

**Comment by mcornella** [comment]
Done: #86. 

Note that there are some other changes that are required to do the full transition to HTTPS everywhere, like changing asset URLs and the `SERVICE_ROOT` variable. 
See the other two commits in [my initial `patch-1` branch](https://github.com/mcornella/formspree/commits/patch-1).

**Comment by colevscode** [comment]
I think moving to https could be a good idea. First we should double check our ssl infrastructure to make sure that it is fast enough. (https://istlsfastyet.com/) If we decide to go forward, I think we should bake the protocol into the SERVICE_ROOT and then eliminate anywhere that we explicitly set the protocol.

**Comment by rohitdatta** [comment]
To actually change all our requests to all use SSL, something like [Flask-SSLify](https://pypi.python.org/pypi/Flask-SSLify) could be used.

**Comment by fiatjaf** [comment]
Let's remember that POSTed forms cannot be redirected.

**Comment by rohitdatta** [comment]
Oh I didn't know that the HTTP protocol didn't allow you to redirect POST requests to HTTPS, which means really all that we need to do if handle any GET requests. This should be easy enough I think. We can inspect the `HTTP_X_FORWARDED_PROTO` and if not made over HTTPS, we can redirect the URL requested to be HTTPS.

I would imagine we would need a config var like `ENABLE_HTTPS` which would be set to false on localhost and servers that don't have an SSL certificate, but set to true on the production server.

**Comment by fiatjaf** [comment]
Closed by https://github.com/formspree/formspree/pull/86
