### ISSUE TITLE
People getting errors when they try to sign up

### ISSUE THREAD

**Issue by RyanKim01** [formspree/formspree#88]
Hello,
I'm hosting a static webpage on Github account. Most of people do not have a problem, but some people always getting error when they click "Sign up" button.

Is there browser dependency or any other dependency which causes an error?

**Comment by rohitdatta** [comment]
Are you saying that this is on your form or on the Formspree website?

**Comment by RyanKim01** [comment]
Sorry for unclarity. It is from my from on my static website. One thing I found that people having problem with Formspree were all using Safari. Weird part is that when I use Formspree on my website using my macbook with Safari, it works fine. But those people are doing same thing in just different laptop and having an error when they send email through Formspree to me. Can you guess what is happening?

**Comment by rohitdatta** [comment]
That seems like it is probably a problem with the site itself. We try to keep issues on the GitHub related to issues that affect the entire Formspree application, so I'm going to close this but if you send an email to team@formspree.io we'd love to help you debug your site.

**Comment by RyanKim01** [comment]
Sounds good. Thank you.
