### ISSUE TITLE
Support for line breaks

### ISSUE THREAD

**Issue by rohitdatta** [formspree/formspree#92]
Support line breaks using the `<pre>` tag as fixed in #48.

**Is this a bug or new feature?** Bug

**Reproduction Steps:**

1. Submit a form with a text area that has line breaks in it.

**Expected behavior:**

Would display in multiple lines in the email.

**Observed behavior:**

Will remove all line breaks and place everything in the same paragraph

**Comment by fiatjaf** [comment]
Just a `<pre>` will do it, no?

**Comment by rohitdatta** [comment]
Oh is that it? I hadn't actually looked at the issue, I just created this so I would actually remember to fix it
